import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Wifi, WifiOff, RotateCcw, Trophy, Target } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { backendApi } from '../services/backendApi';

type Props={gameType:'pool'|'carrom'};
type Ball={x:number;y:number;vx:number;vy:number;r:number;color:string;num:number;pocketed?:boolean};
const W=360,H=620;
const WS_URL=(import.meta.env.VITE_LIVE_WS_URL || '').replace(/\/$/,'');
function wsUrl(matchId:string){ if(WS_URL) return `${WS_URL}/live?matchId=${encodeURIComponent(matchId)}&token=${encodeURIComponent(localStorage.getItem('skillz_api_token')||'')}`; const p=location.protocol==='https:'?'wss':'ws'; return `${p}://${location.host}/live?matchId=${encodeURIComponent(matchId)}&token=${encodeURIComponent(localStorage.getItem('skillz_api_token')||'')}`; }
function dist(a:Ball,b:Ball){return Math.hypot(a.x-b.x,a.y-b.y)}
function initialPool():Ball[]{const out:Ball[]=[]; out.push({x:180,y:475,vx:0,vy:0,r:8,color:'#f8fafc',num:0}); let n=1; const rows=[3,4,5,4,3]; for(let row=0;row<5;row++){for(let j=0;j<rows[row];j++){out.push({x:180+(j-(rows[row]-1)/2)*18,y:150+row*16,vx:0,vy:0,r:7,color:n===8?'#111827':(n%2?'#eab308':'#ef4444'),num:n++});}} return out;}
function initialCarrom():Ball[]{const out:Ball[]=[]; out.push({x:180,y:545,vx:0,vy:0,r:9,color:'#f8fafc',num:0}); out.push({x:180,y:310,vx:0,vy:0,r:8,color:'#ef4444',num:99}); for(let i=0;i<18;i++){const a=i*Math.PI/9;const rr=i<6?28:i<12?48:68;out.push({x:180+Math.cos(a)*rr,y:310+Math.sin(a)*rr,vx:0,vy:0,r:7,color:i%2?'#111827':'#f8fafc',num:i+1});} return out;}

export const ArcadeOnlineGame:React.FC<Props>=({gameType})=>{
 const {setCurrentTab,user}=useApp(); const canvas=useRef<HTMLCanvasElement>(null); const ws=useRef<WebSocket|null>(null); const raf=useRef(0); const balls=useRef<Ball[]>(gameType==='pool'?initialPool():initialCarrom()); const [match,setMatch]=useState<any>(null); const [waiting,setWaiting]=useState(false); const [connected,setConnected]=useState(false); const [myTurn,setMyTurn]=useState(false); const [aim,setAim]=useState({x:180,y:475}); const [power,setPower]=useState(0); const [winner,setWinner]=useState<string|null>(null); const [msg,setMsg]=useState(''); const [starting,setStarting]=useState(false); const drag=useRef(false); const last=useRef({x:0,y:0}); const turnBusy=useRef(false);
 const label=gameType==='pool'?'8 Ball Pool':'Carrom';
 const reset=()=>{balls.current=gameType==='pool'?initialPool():initialCarrom();setWinner(null);setPower(0);setMsg('');};
 const start=async()=>{if(starting)return;setStarting(true);try{const d=await backendApi.arcadeStart(gameType);setMatch(d.match);setWaiting(!d.paired);if(d.paired) setMyTurn((d.match.playerNumber||1)===1);}catch(e:any){setMsg(e.message||'Match শুরু করা যায়নি।');}finally{setStarting(false);}};
 useEffect(()=>{start();return()=>{ws.current?.close();cancelAnimationFrame(raf.current)}},[]);
 useEffect(()=>{if(!match?.id||!waiting)return; let alive=true; const poll=async()=>{try{const d=await backendApi.arcadeMatch(match.id);if(!alive)return;setMatch(d.match);if(d.match.status==='PLAYING'){setWaiting(false);setMyTurn((d.match.playerNumber||1)===1);}}catch{}}; poll(); const t=window.setInterval(poll,1200); return()=>{alive=false;window.clearInterval(t)}},[match?.id,waiting]);
 useEffect(()=>{if(!match?.id||match.status!=='PLAYING')return; const socket=new WebSocket(wsUrl(match.id));ws.current=socket;socket.onopen=()=>setConnected(true);socket.onclose=()=>setConnected(false);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='ARCADE_READY'){setConnected(true);return;} if(m.type==='ARCADE_SHOT'&&m.userId!==user.id){applyRemote(m);} if(m.type==='ARCADE_FINISH'&&m.userId!==user.id){setWinner(m.winner);}};return()=>socket.close()},[match?.id,match?.status,user.id]);
 function applyRemote(m:any){balls.current=(m.balls||balls.current).map((b:any)=>({...b}));turnBusy.current=true;setMyTurn(false);setPower(0);}
 function sendShot(){if(!myTurn||winner||power<0.04)return; const cue=balls.current[0]; const target=aim; const dx=cue.x-target.x,dy=cue.y-target.y;const len=Math.hypot(dx,dy)||1;const max=gameType==='pool'?9:7;cue.vx=(dx/len)*power*max;cue.vy=(dy/len)*power*max; const payload={type:'ARCADE_SHOT',balls:balls.current,playerNumber:match.playerNumber,shot:{x:cue.x,y:cue.y,vx:cue.vx,vy:cue.vy}};ws.current?.send(JSON.stringify(payload));turnBusy.current=true;setMyTurn(false);setPower(0);}
 const finish=async(w:'P1'|'P2'|'DRAW')=>{if(winner)return;setWinner(w);ws.current?.send(JSON.stringify({type:'ARCADE_FINISH',winner:w}));try{await backendApi.arcadeFinish(match.id,w);}catch{} };
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;const tick=()=>{raf.current=requestAnimationFrame(tick);const arr=balls.current;let moving=false;for(const b of arr){if(b.pocketed)continue;if(Math.abs(b.vx)+Math.abs(b.vy)>0.02){moving=true;b.x+=b.vx;b.y+=b.vy;b.vx*=0.985;b.vy*=0.985;const left=gameType==='pool'?28:24,right=W-left,top=gameType==='pool'?40:24,bottom=H-(gameType==='pool'?40:24);if(b.x<left+b.r){b.x=left+b.r;b.vx=Math.abs(b.vx)*0.96}if(b.x>right-b.r){b.x=right-b.r;b.vx=-Math.abs(b.vx)*0.96}if(b.y<top+b.r){b.y=top+b.r;b.vy=Math.abs(b.vy)*0.96}if(b.y>bottom-b.r){b.y=bottom-b.r;b.vy=-Math.abs(b.vy)*0.96}}
 }
 const pockets=gameType==='pool'?[{x:29,y:41},{x:331,y:41},{x:29,y:579},{x:331,y:579}]:[{x:29,y:29},{x:331,y:29},{x:29,y:591},{x:331,y:591}];
 for(const b of arr){if(b.pocketed)continue;for(const p of pockets){if(Math.hypot(b.x-p.x,b.y-p.y)<(gameType==='pool'?15:13)){b.pocketed=true;b.vx=0;b.vy=0;break;}}}
 for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const a=arr[i],b=arr[j];if(a.pocketed||b.pocketed)continue;const d=dist(a,b),min=a.r+b.r;if(d>0&&d<min){const nx=(b.x-a.x)/d,ny=(b.y-a.y)/d,rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny}const push=(min-d)/2;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push;}}
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#07502f';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#c89b5a';ctx.lineWidth=10;ctx.strokeRect(24,gameType==='pool'?36:20,W-48,H-(gameType==='pool'?72:40));const drawPockets=gameType==='pool'?[{x:29,y:41},{x:331,y:41},{x:29,y:579},{x:331,y:579}]:[{x:29,y:29},{x:331,y:29},{x:29,y:591},{x:331,y:591}];for(const p of drawPockets){ctx.beginPath();ctx.fillStyle='#090b10';ctx.arc(p.x,p.y,gameType==='pool'?14:12,0,Math.PI*2);ctx.fill();}
 if(gameType==='carrom'){ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(180,310,75,0,Math.PI*2);ctx.stroke();}
 for(const b of arr){if(b.pocketed)continue;ctx.beginPath();ctx.fillStyle=b.color;ctx.shadowBlur=6;ctx.shadowColor='rgba(0,0,0,.7)';ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(gameType==='pool'&&b.num>0&&b.num!==8){ctx.fillStyle='#fff';ctx.font='7px sans-serif';ctx.textAlign='center';ctx.fillText(String(b.num),b.x,b.y+2.5)}}
 ctx.fillStyle='rgba(255,255,255,.9)';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(myTurn&&!winner?'YOUR TURN':'OPPONENT TURN',180,18); if(!moving && turnBusy.current && !winner && match?.status==='PLAYING'){turnBusy.current=false;setMyTurn(true)} if(gameType==='pool'){const solids=arr.filter(b=>b.num>0&&b.num!==8&&!b.pocketed).length;if(solids===0&&arr.find(b=>b.num===8)?.pocketed)finish((match?.playerNumber||1)===1?'P1':'P2');} else { const remaining=arr.filter(b=>b.num>0&&b.num!==99&&!b.pocketed).length; if(remaining===0) finish((match?.playerNumber||1)===1?'P1':'P2'); }
 };tick();return()=>cancelAnimationFrame(raf.current)},[gameType,match?.status,myTurn,winner]);
 const pointer=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();const x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(!drag.current){drag.current=true;last.current={x,y};}const dx=x-last.current.x,dy=y-last.current.y;const cue=balls.current[0];if(myTurn&&!winner){setAim({x,y});setPower(Math.min(1,Math.max(0,Math.hypot(cue.x-x,cue.y-y)/140)));}last.current={x,y};};
 return <div className="min-h-screen bg-[#07140f] text-white px-3 pt-2 pb-24"><div className="flex items-center justify-between mb-3"><button onClick={()=>setCurrentTab('home')} className="p-2 rounded-xl bg-white/5"><ArrowLeft/></button><div className="text-center"><h2 className="font-black text-lg">{gameType==='pool'?'🎱':'🪙'} {label}</h2><p className="text-[10px] text-slate-400">{connected?<><Wifi className="inline w-3 h-3 mr-1"/>ONLINE</>:<><WifiOff className="inline w-3 h-3 mr-1"/>CONNECTING</>}</p></div><div className="w-10"/></div>
 {waiting&&<div className="mb-3 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-3 text-center text-sm">Opponent খোঁজা হচ্ছে…<br/><span className="text-xs text-slate-400">Entry Fee ৳{Number(match?.entryFee||0).toFixed(0)}</span></div>}
 <div className="relative mx-auto w-full max-w-[360px] rounded-3xl overflow-hidden shadow-2xl border border-amber-900/60"><canvas ref={canvas} width={W} height={H} className="w-full touch-none" onPointerDown={pointer} onPointerMove={pointer} onPointerUp={()=>{drag.current=false;sendShot()}} /></div>
 <div className="mt-3 rounded-2xl bg-[#10221a] border border-emerald-900/60 p-3"><div className="flex justify-between text-xs"><span>Entry ৳{Number(match?.entryFee||0).toFixed(0)}</span><span>Prize ৳{Number(match?.prizeAmount||0).toFixed(0)}</span><span>{myTurn?'আপনার Turn':'Opponent Turn'}</span></div><div className="mt-2 h-2 bg-black/30 rounded-full overflow-hidden"><div className="h-full bg-amber-400 transition-all" style={{width:`${power*100}%`}}/></div></div>
 {winner&&<div className="mt-3 rounded-2xl bg-amber-500/15 border border-amber-500/40 p-4 text-center"><Trophy className="mx-auto text-amber-300"/><b className="block mt-1">{winner==='DRAW'?'DRAW':winner===`P${match?.playerNumber}`?'YOU WIN 🎉':'YOU LOSE'}</b><button onClick={()=>{reset();start()}} className="mt-3 px-5 py-2 rounded-xl bg-amber-400 text-slate-950 font-black"><RotateCcw className="inline w-4 h-4 mr-1"/>REPLAY</button></div>}
 {msg&&<div className="mt-3 text-center text-red-300 text-xs">{msg}</div>}
 <div className="mt-3 text-[10px] text-slate-500 text-center">Smooth touch control • Real-time online match • Server match/entry/payout</div></div>;
};
