const API_BASE = (import.meta.env.VITE_API_BASE_URL || '/api').replace(/\/$/, '');
function token() { return localStorage.getItem('skillz_api_token') || ''; }
async function request<T>(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  const t = token(); if (t) headers.set('Authorization', `Bearer ${t}`);
  const res = await fetch(`${API_BASE}${path}`, { ...options, headers });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.message || `HTTP ${res.status}`);
  return data as T;
}
export const backendApi = {
  health: () => request<{ ok: boolean; database: string }>('/health'),
  login: (phone: string, password: string) => request<{ token: string; user: any }>('/auth/login', { method: 'POST', body: JSON.stringify({ phone, password }) }),
  register: (name: string, phone: string, password: string, refCode = '') => request<{ token: string; user: any }>('/auth/register', { method: 'POST', body: JSON.stringify({ name, phone, password, refCode }) }),
  me: () => request<{ user: any }>('/me'),
  users: () => request<{ users: any[] }>('/users'),
  matches: () => request<{ matches: any[] }>('/matches'),
  transactions: () => request<{ transactions: any[] }>('/transactions'),
  adminBlockPuzzleMatches: () => request<{ matches: any[] }>('/admin/block-puzzle/matches'),
  adminUserAudit: (id: string) => request<any>(`/admin/users/${encodeURIComponent(id)}/audit`),
  games: () => request<{ games: any[] }>('/games'),
  adminGames: () => request<{ games: any[] }>('/admin/games'),
  createGame: (payload: any) => request<{ game: any }>('/admin/games', { method: 'POST', body: JSON.stringify(payload) }),
  updateGame: (id: string, payload: any) => request<{ game: any }>(`/admin/games/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(payload) }),
  deleteGame: (id: string) => request<{ ok: boolean }>(`/admin/games/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  tournaments: () => request<{ tournaments: any[] }>('/tournaments'),
  adminTournaments: () => request<{ tournaments: any[] }>('/admin/tournaments'),
  createTournament: (payload: any) => request<{ tournament: any }>('/admin/tournaments', { method: 'POST', body: JSON.stringify(payload) }),
  updateTournament: (id: string, payload: any) => request<{ tournament: any }>(`/admin/tournaments/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(payload) }),
  deleteTournament: (id: string) => request<{ ok: boolean }>(`/admin/tournaments/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  finalizeTournament: (id: string) => request<{ tournament: any; payouts: any[] }>(`/admin/tournaments/${encodeURIComponent(id)}/finalize`, { method: 'POST' }),
  approveTournamentPayouts: (id: string, userIds?: string[]) => request<{ tournament: any; approved: number; pending: boolean; paid: number; held: number; payouts: any[] }>(`/admin/tournaments/${encodeURIComponent(id)}/payout-approval`, { method: 'POST', body: JSON.stringify({ userIds }) }),
  holdTournamentPayout: (id: string, userId: string, reason = '') => request<{ tournament: any }>(`/admin/tournaments/${encodeURIComponent(id)}/hold-payout`, { method: 'POST', body: JSON.stringify({ userId, reason }) }),
  joinTournament: (id: string) => request<{ tournament: any; match: any; user: any }>(`/tournaments/${encodeURIComponent(id)}/join`, { method: 'POST' }),
  tournament: (id: string) => request<{ tournament: any }>(`/tournaments/${encodeURIComponent(id)}`),
  createMatch: (match: any) => request<{ match: any }>('/matches', { method: 'POST', body: JSON.stringify(match) }),
  joinMatch: (id: string, ludoKingName: string) => request<{ match: any; user: any }>(`/matches/${id}/join`, { method: 'POST', body: JSON.stringify({ ludoKingName }) }),
  setRoom: (id: string, roomCode: string) => request<{ match: any }>(`/matches/${id}/room`, { method: 'PATCH', body: JSON.stringify({ roomCode }) }),
  deleteMatch: (id: string) => request<{ ok: boolean }>(`/matches/${id}`, { method: 'DELETE' }),
  cancelMatch: (id: string, reason = '') => request<{ match: any }>(`/matches/${id}/cancel`, { method: 'POST', body: JSON.stringify({ reason }) }),
  deleteAdminBlockPuzzleMatch: (id: string) => request<{ ok: boolean }>(`/admin/block-puzzle/matches/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  adjustBalance: (id: string, balanceType: string, amount: number, isAddition: boolean, note = '', adjustmentId = '') => request<{ user: any; duplicate?: boolean }>(`/users/${id}/balance`, { method: 'POST', body: JSON.stringify({ balanceType, amount, isAddition, note, adjustmentId }) }),
  toggleBan: (id: string, banned: boolean) => request<{ user: any }>(`/users/${id}/ban`, { method: 'PATCH', body: JSON.stringify({ banned }) }),
  deleteUser: (id: string) => request<{ ok: boolean }>(`/users/${id}`, { method: 'DELETE' }),
  resetPassword: (id: string, password: string) => request<{ user: any }>(`/users/${id}/password-reset`, { method: 'POST', body: JSON.stringify({ password }) }),
  depositRequests: () => request<{ depositRequests: any[] }>('/deposit-requests'),
  withdrawRequests: () => request<{ withdrawRequests: any[] }>('/withdraw-requests'),
  resultSubmissions: () => request<{ resultSubmissions: any[] }>('/result-submissions'),
  myRequests: () => request<{ depositRequests: any[]; withdrawRequests: any[]; resultSubmissions: any[] }>('/my-requests'),
  createDeposit: (payload: any) => request<{ request: any }>('/deposit-requests', { method: 'POST', body: JSON.stringify(payload) }),
  updateDeposit: (id: string, status: string, reason = '') => request<{ request: any; user?: any }>(`/deposit-requests/${id}`, { method: 'PATCH', body: JSON.stringify({ status, reason }) }),
  deleteDeposit: (id: string) => request<{ ok: boolean }>(`/deposit-requests/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  createWithdraw: (payload: any) => request<{ request: any; user: any }>('/withdraw-requests', { method: 'POST', body: JSON.stringify(payload) }),
  updateWithdraw: (id: string, status: string, adminTrxId = '', reason = '') => request<{ request: any; user?: any }>(`/withdraw-requests/${id}`, { method: 'PATCH', body: JSON.stringify({ status, adminTrxId, reason }) }),
  reviewWithdraw: (id: string, note = '') => request<{ request: any }>(`/withdraw-requests/${encodeURIComponent(id)}/review`, { method: 'POST', body: JSON.stringify({ note }) }),
  deleteWithdraw: (id: string) => request<{ ok: boolean }>(`/withdraw-requests/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  createResult: (payload: any) => request<{ submission: any }>('/result-submissions', { method: 'POST', body: JSON.stringify(payload) }),
  arcadeStart: (gameType: 'pool' | 'carrom') => request<{ match: any; user: any; paired: boolean }>('/arcade/matches/start', { method: 'POST', body: JSON.stringify({ gameType }) }),
  arcadeMatch: (id: string) => request<{ match: any; user: any }>(`/arcade/matches/${encodeURIComponent(id)}`),
  arcadeFinish: (id: string, winner: 'P1' | 'P2' | 'DRAW') => request<{ match: any; user: any }>(`/arcade/matches/${encodeURIComponent(id)}/finish`, { method: 'POST', body: JSON.stringify({ winner }) }),
  activeBlockPuzzleMatch: () => request<{ match: any | null }>('/block-puzzle/matches/active'),
  myBlockPuzzleMatches: () => request<{ matches: any[] }>('/block-puzzle/matches/mine'),
  pendingGames: () => request<{ items: any[] }>('/pending-games'),
  activeBlockPuzzleLeaderboard: () => request<{ leaderboard: any | null }>('/block-puzzle/leaderboard/active'),
  adminBlockPuzzleLeaderboards: () => request<{ leaderboards: any[] }>('/admin/block-puzzle/leaderboards'),
  createBlockPuzzleLeaderboard: (payload: any) => request<{ leaderboard: any }>('/admin/block-puzzle/leaderboards', { method: 'POST', body: JSON.stringify(payload) }),
  finalizeBlockPuzzleLeaderboard: (id: string) => request<{ leaderboard: any; payouts: any[] }>(`/admin/block-puzzle/leaderboards/${encodeURIComponent(id)}/finalize`, { method: 'POST' }),
  blockPuzzleMatchStatus: (matchId: string) => request<{ match: any | null; user?: any }>(`/block-puzzle/matches/${encodeURIComponent(matchId)}/status`),
  startBlockPuzzleMatch: (entryFee: number, prizeAmount: number, playerCount = 2) => request<{ match: any; user: any }>('/block-puzzle/matches/start', { method: 'POST', body: JSON.stringify({ entryFee, prizeAmount, playerCount }) }),
  submitBlockPuzzleMatch: (matchId: string, score: number, linesCleared = 0, bestCombo = 0) => request<{ match: any; user: any }>(`/block-puzzle/matches/${encodeURIComponent(matchId)}/submit`, { method: 'POST', body: JSON.stringify({ score, linesCleared, bestCombo }) }),
  refundBlockPuzzleMatch: (matchId: string, reason = '') => request<{ match: any; user: any }>('/block-puzzle/matches/' + encodeURIComponent(matchId) + '/refund', { method: 'POST', body: JSON.stringify({ reason }) }),
  createBlockPuzzleResult: (payload: { matchId: string; score: number; prizeAmount: number; linesCleared?: number; bestCombo?: number; imageUrl?: string }) => request<{ submission: any; match?: any }>('/result-submissions', { method: 'POST', body: JSON.stringify({ ...payload, gameType: 'block_puzzle' }) }),
  updateResult: (id: string, status: string, reason = '') => request<{ submission: any; user?: any }>(`/result-submissions/${id}`, { method: 'PATCH', body: JSON.stringify({ status, reason }) }),
  transferWinning: (amount: number) => request<{ user: any }>('/winning/transfer', { method: 'POST', body: JSON.stringify({ amount }) }),
  settings: () => request<{ paymentSettings: any; referralSettings?: any }>('/settings'),
  updateSettings: (settings: any) => request<{ paymentSettings: any; referralSettings?: any }>('/settings', { method: 'PATCH', body: JSON.stringify(settings) }),
  referralSummary: () => request<{ settings: any; summary: any; referrals: any[] }>('/referral/summary'),
  adminReferrals: () => request<{ settings: any; referrals: any[] }>('/admin/referrals'),
  approveAdminReferral: (id: string) => request<{ referral: any; user?: any }>(`/admin/referrals/${encodeURIComponent(id)}/approve`, { method: 'POST' }),
  rejectAdminReferral: (id: string, reason = '') => request<{ referral: any }>(`/admin/referrals/${encodeURIComponent(id)}/reject`, { method: 'POST', body: JSON.stringify({ reason }) }),
};
